spring:
  cloud:
    gateway:
      routes:
        - id: api-microservice-one
          uri: ${microservice.one.url}
          predicates:
            - Path=/api/microservice-one/**
          filters:
            - name: CustomJwt
              args:
                jwtTokenGenerator: "#{@jwtTokenGenerator}"
            - name: CircuitBreaker
              args:
                name: ${circuit.breaker.identifier.default}
                fallbackUri: forward:/fallback

        - id: default
          uri: ${microservice.default.url}
          predicates:
            - Path=/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

logging:
  level:
    org.springframwork.cloud.gateway: ${log.level:INFO}
    org.springframwork.http.server.reactive: ${log.level:INFO}
    org.springframwork.web.reactive: ${log.level:INFO}
    reactor.ipc.netty: ${log.level:INFO}
    reactor.netty: ${log.level:INFO}